name: allthingstech
favicon: null
layout_spectrum: 0.9158165820408612
typography_spectrum: 0.9782850183546543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4868113724514842
  lightness: 0.29383257078006864
  saturation: 0.7669936472084373
  rhythmicContrast: 0.7849018406122923
purpose: []
